<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Financial Mathematics Research">
<meta name="dcterms.date" content="2026-01-27">

<title>Empirical Examination of the Black–Scholes Model</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="pde3_files/libs/clipboard/clipboard.min.js"></script>
<script src="pde3_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="pde3_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="pde3_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="pde3_files/libs/quarto-html/popper.min.js"></script>
<script src="pde3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="pde3_files/libs/quarto-html/anchor.min.js"></script>
<link href="pde3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="pde3_files/libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="pde3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="pde3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="pde3_files/libs/bootstrap/bootstrap-8c4b283fe68d871141289ba1f5d31ced.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background"><span class="header-section-number">1.1</span> Background</a></li>
  <li><a href="#research-objective" id="toc-research-objective" class="nav-link" data-scroll-target="#research-objective"><span class="header-section-number">1.2</span> Research Objective</a></li>
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses"><span class="header-section-number">1.3</span> Hypotheses</a></li>
  </ul></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology"><span class="header-section-number">2</span> Methodology</a>
  <ul class="collapse">
  <li><a href="#the-blackscholes-model" id="toc-the-blackscholes-model" class="nav-link" data-scroll-target="#the-blackscholes-model"><span class="header-section-number">2.1</span> The Black–Scholes Model</a></li>
  <li><a href="#implied-volatility-estimation" id="toc-implied-volatility-estimation" class="nav-link" data-scroll-target="#implied-volatility-estimation"><span class="header-section-number">2.2</span> Implied Volatility Estimation</a></li>
  <li><a href="#statistical-testing" id="toc-statistical-testing" class="nav-link" data-scroll-target="#statistical-testing"><span class="header-section-number">2.3</span> Statistical Testing</a></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">3</span> Data</a>
  <ul class="collapse">
  <li><a href="#stock-selection" id="toc-stock-selection" class="nav-link" data-scroll-target="#stock-selection"><span class="header-section-number">3.1</span> Stock Selection</a></li>
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources"><span class="header-section-number">3.2</span> Data Sources</a></li>
  </ul></li>
  <li><a href="#empirical-results" id="toc-empirical-results" class="nav-link" data-scroll-target="#empirical-results"><span class="header-section-number">4</span> Empirical Results</a>
  <ul class="collapse">
  <li><a href="#stock-price-trend-analysis" id="toc-stock-price-trend-analysis" class="nav-link" data-scroll-target="#stock-price-trend-analysis"><span class="header-section-number">4.1</span> Stock Price Trend Analysis</a>
  <ul class="collapse">
  <li><a href="#interpretation-stock-price-trends" id="toc-interpretation-stock-price-trends" class="nav-link" data-scroll-target="#interpretation-stock-price-trends"><span class="header-section-number">4.1.1</span> Interpretation: Stock Price Trends</a></li>
  </ul></li>
  <li><a href="#blackscholes-model-implementation-and-pricing" id="toc-blackscholes-model-implementation-and-pricing" class="nav-link" data-scroll-target="#blackscholes-model-implementation-and-pricing"><span class="header-section-number">4.2</span> Black–Scholes Model Implementation and Pricing</a></li>
  <li><a href="#paired-sample-t-test-results" id="toc-paired-sample-t-test-results" class="nav-link" data-scroll-target="#paired-sample-t-test-results"><span class="header-section-number">4.3</span> Paired Sample T-Test Results</a>
  <ul class="collapse">
  <li><a href="#call-options" id="toc-call-options" class="nav-link" data-scroll-target="#call-options"><span class="header-section-number">4.3.1</span> Call Options</a></li>
  <li><a href="#put-options" id="toc-put-options" class="nav-link" data-scroll-target="#put-options"><span class="header-section-number">4.3.2</span> Put Options</a></li>
  <li><a href="#results-visualization-p-values-by-stock" id="toc-results-visualization-p-values-by-stock" class="nav-link" data-scroll-target="#results-visualization-p-values-by-stock"><span class="header-section-number">4.3.3</span> Results Visualization: P-Values by Stock</a></li>
  <li><a href="#interpretation-p-value-analysis" id="toc-interpretation-p-value-analysis" class="nav-link" data-scroll-target="#interpretation-p-value-analysis"><span class="header-section-number">4.3.4</span> Interpretation: P-Value Analysis</a></li>
  </ul></li>
  <li><a href="#pricing-error-analysis" id="toc-pricing-error-analysis" class="nav-link" data-scroll-target="#pricing-error-analysis"><span class="header-section-number">4.4</span> Pricing Error Analysis</a>
  <ul class="collapse">
  <li><a href="#distribution-of-pricing-errors-by-stock" id="toc-distribution-of-pricing-errors-by-stock" class="nav-link" data-scroll-target="#distribution-of-pricing-errors-by-stock"><span class="header-section-number">4.4.1</span> Distribution of Pricing Errors by Stock</a></li>
  <li><a href="#interpretation-error-distribution" id="toc-interpretation-error-distribution" class="nav-link" data-scroll-target="#interpretation-error-distribution"><span class="header-section-number">4.4.2</span> Interpretation: Error Distribution</a></li>
  <li><a href="#mean-pricing-error-by-stock" id="toc-mean-pricing-error-by-stock" class="nav-link" data-scroll-target="#mean-pricing-error-by-stock"><span class="header-section-number">4.4.3</span> Mean Pricing Error by Stock</a></li>
  <li><a href="#interpretation-mean-pricing-errors" id="toc-interpretation-mean-pricing-errors" class="nav-link" data-scroll-target="#interpretation-mean-pricing-errors"><span class="header-section-number">4.4.4</span> Interpretation: Mean Pricing Errors</a></li>
  <li><a href="#standard-deviation-of-pricing-errors" id="toc-standard-deviation-of-pricing-errors" class="nav-link" data-scroll-target="#standard-deviation-of-pricing-errors"><span class="header-section-number">4.4.5</span> Standard Deviation of Pricing Errors</a></li>
  <li><a href="#interpretation-standard-deviation-analysis" id="toc-interpretation-standard-deviation-analysis" class="nav-link" data-scroll-target="#interpretation-standard-deviation-analysis"><span class="header-section-number">4.4.6</span> Interpretation: Standard Deviation Analysis</a></li>
  </ul></li>
  <li><a href="#sector-analysis" id="toc-sector-analysis" class="nav-link" data-scroll-target="#sector-analysis"><span class="header-section-number">4.5</span> Sector Analysis</a>
  <ul class="collapse">
  <li><a href="#interpretation-sector-analysis" id="toc-interpretation-sector-analysis" class="nav-link" data-scroll-target="#interpretation-sector-analysis"><span class="header-section-number">4.5.1</span> Interpretation: Sector Analysis</a></li>
  </ul></li>
  <li><a href="#market-vs-black-scholes-price-comparison" id="toc-market-vs-black-scholes-price-comparison" class="nav-link" data-scroll-target="#market-vs-black-scholes-price-comparison"><span class="header-section-number">4.6</span> Market vs Black-Scholes Price Comparison</a>
  <ul class="collapse">
  <li><a href="#interpretation-market-vs-bs-price-scatter" id="toc-interpretation-market-vs-bs-price-scatter" class="nav-link" data-scroll-target="#interpretation-market-vs-bs-price-scatter"><span class="header-section-number">4.6.1</span> Interpretation: Market vs BS Price Scatter</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#summary-and-conclusions" id="toc-summary-and-conclusions" class="nav-link" data-scroll-target="#summary-and-conclusions"><span class="header-section-number">5</span> Summary and Conclusions</a>
  <ul class="collapse">
  <li><a href="#summary-of-results" id="toc-summary-of-results" class="nav-link" data-scroll-target="#summary-of-results"><span class="header-section-number">5.1</span> Summary of Results</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">5.2</span> Conclusions</a>
  <ul class="collapse">
  <li><a href="#primary-findings" id="toc-primary-findings" class="nav-link" data-scroll-target="#primary-findings"><span class="header-section-number">5.2.1</span> Primary Findings</a></li>
  <li><a href="#comparison-with-prior-research" id="toc-comparison-with-prior-research" class="nav-link" data-scroll-target="#comparison-with-prior-research"><span class="header-section-number">5.2.2</span> Comparison with Prior Research</a></li>
  <li><a href="#possible-reasons-for-model-mispricing" id="toc-possible-reasons-for-model-mispricing" class="nav-link" data-scroll-target="#possible-reasons-for-model-mispricing"><span class="header-section-number">5.2.3</span> Possible Reasons for Model Mispricing</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#future-work" id="toc-future-work" class="nav-link" data-scroll-target="#future-work"><span class="header-section-number">6</span> Future Work</a>
  <ul class="collapse">
  <li><a href="#alternative-pricing-models" id="toc-alternative-pricing-models" class="nav-link" data-scroll-target="#alternative-pricing-models"><span class="header-section-number">6.1</span> 1. Alternative Pricing Models</a></li>
  <li><a href="#extended-empirical-analysis" id="toc-extended-empirical-analysis" class="nav-link" data-scroll-target="#extended-empirical-analysis"><span class="header-section-number">6.2</span> 2. Extended Empirical Analysis</a></li>
  <li><a href="#machine-learning-approaches" id="toc-machine-learning-approaches" class="nav-link" data-scroll-target="#machine-learning-approaches"><span class="header-section-number">6.3</span> 3. Machine Learning Approaches</a></li>
  <li><a href="#market-condition-analysis" id="toc-market-condition-analysis" class="nav-link" data-scroll-target="#market-condition-analysis"><span class="header-section-number">6.4</span> 4. Market Condition Analysis</a></li>
  <li><a href="#practical-applications" id="toc-practical-applications" class="nav-link" data-scroll-target="#practical-applications"><span class="header-section-number">6.5</span> 5. Practical Applications</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">7</span> References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Empirical Examination of the Black–Scholes Model</h1>
<p class="subtitle lead">Evidence from the United States Stock Market</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Financial Mathematics Research </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 27, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<section id="background" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="background"><span class="header-section-number">1.1</span> Background</h2>
<p>Option pricing is crucial in enabling investors to hedge against risks in financial markets. The Black–Scholes option pricing model, developed by Fischer Black, Myron Scholes, and Robert Merton in 1973, remains one of the most widely used frameworks for pricing European-style options. This groundbreaking work earned Scholes and Merton the 1997 Nobel Prize in Economics.</p>
<p>The Black–Scholes model provides a theoretical framework for determining the fair price of options based on several key factors: the current stock price, strike price, time to expiration, risk-free interest rate, and volatility of the underlying asset. Despite its widespread adoption, the model relies on several simplifying assumptions that may not hold in real financial markets, including constant volatility, continuous trading, and log-normally distributed returns.</p>
</section>
<section id="research-objective" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="research-objective"><span class="header-section-number">1.2</span> Research Objective</h2>
<p>This study investigates whether the Black–Scholes model is a good indicator of option pricing in the United States stock market. Following the methodology of Salami (2024), we examine the relevance of the Black–Scholes model to selected stocks using paired sample t-tests and the Corrado-Miller approximation for implied volatility.</p>
<p>The primary research questions are:</p>
<ol type="1">
<li>Is there a significant difference between actual market option prices and Black–Scholes theoretical prices?</li>
<li>Does the model perform differently for call options versus put options?</li>
<li>Are there systematic patterns in pricing errors across different stocks and sectors?</li>
</ol>
</section>
<section id="hypotheses" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="hypotheses"><span class="header-section-number">1.3</span> Hypotheses</h2>
<p>The hypotheses tested in this study are:</p>
<p><span class="math display">\[
H_0: \text{There is no significant difference between the actual market premium and the Black–Scholes premium}
\]</span></p>
<p><span class="math display">\[
H_1: \text{There is a significant difference between the actual market premium and the Black–Scholes premium}
\]</span></p>
<p>The null hypothesis is rejected at the 95% confidence level if the p-value is less than 0.05.</p>
<div id="setup" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm, ttest_rel, ttest_1samp</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> brentq</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> datetime <span class="im">import</span> datetime, timedelta</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot settings</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>plt.style.use(<span class="st">'seaborn-v0_8-whitegrid'</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>sns.set_palette(<span class="st">"husl"</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> (<span class="dv">12</span>, <span class="dv">6</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">'font.size'</span>] <span class="op">=</span> <span class="dv">11</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<hr>
</section>
</section>
<section id="methodology" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Methodology</h1>
<section id="the-blackscholes-model" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="the-blackscholes-model"><span class="header-section-number">2.1</span> The Black–Scholes Model</h2>
<p>The classical Black–Scholes model applies to non-dividend-paying assets and European-style options. However, this study uses the extended Black–Scholes model first introduced by Merton (1973), which incorporates dividend yields and can be applied to American-style options under certain conditions.</p>
<p>The extended Black–Scholes formulas for call and put options at time <span class="math inline">\(t\)</span> are:</p>
<p><strong>Call Option Premium:</strong> <span class="math display">\[
C_t = S_t e^{-\delta T} \Phi(d_1) - K e^{-rT} \Phi(d_2)
\]</span></p>
<p><strong>Put Option Premium:</strong> <span class="math display">\[
P_t = K e^{-rT} \Phi(-d_2) - S_t e^{-\delta T} \Phi(-d_1)
\]</span></p>
<p>where: <span class="math display">\[
d_1 = \frac{\ln(S_t/K) + (r - \delta + \sigma^2/2)T}{\sigma\sqrt{T}}
\]</span> <span class="math display">\[
d_2 = d_1 - \sigma\sqrt{T}
\]</span></p>
<p>The variables are defined as:</p>
<ul>
<li><span class="math inline">\(S_t\)</span> = Current stock price</li>
<li><span class="math inline">\(K\)</span> = Strike price</li>
<li><span class="math inline">\(T\)</span> = Time to expiration (in years)</li>
<li><span class="math inline">\(r\)</span> = Risk-free interest rate</li>
<li><span class="math inline">\(\delta\)</span> = Dividend yield</li>
<li><span class="math inline">\(\sigma\)</span> = Volatility</li>
<li><span class="math inline">\(\Phi(\cdot)\)</span> = Cumulative standard normal distribution function</li>
</ul>
</section>
<section id="implied-volatility-estimation" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="implied-volatility-estimation"><span class="header-section-number">2.2</span> Implied Volatility Estimation</h2>
<p>Since volatility is not directly observable, this study uses the Corrado-Miller (1996) approximation to estimate implied volatility from observed market prices.</p>
<p>For a call option, the implied volatility is approximated as:</p>
<p><span class="math display">\[
\sigma \approx \frac{\sqrt{2\pi}}{S e^{-\delta T} + K e^{-rT}} \left[ c_m - \frac{S e^{-\delta T} - K e^{-rT}}{2} + \sqrt{\left(c_m - \frac{S e^{-\delta T} - K e^{-rT}}{2}\right)^2 - \frac{(S e^{-\delta T} - K e^{-rT})^2}{\pi}} \right] / \sqrt{T}
\]</span></p>
<p>where <span class="math inline">\(c_m\)</span> is the market premium for the call option. A similar formula applies for put options, with appropriate sign changes.</p>
</section>
<section id="statistical-testing" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="statistical-testing"><span class="header-section-number">2.3</span> Statistical Testing</h2>
<p>The paired sample t-test compares the mean difference between actual market premiums and Black–Scholes model premiums with zero. For sample sizes greater than 30, the normality assumption can be relaxed according to the Central Limit Theorem, as noted by Ghasemi and Zahediasl (2012).</p>
<p>The test statistic is: <span class="math display">\[
t = \frac{\bar{D}}{s_D / \sqrt{n}}
\]</span></p>
<p>where <span class="math inline">\(\bar{D}\)</span> is the mean difference, <span class="math inline">\(s_D\)</span> is the standard deviation of differences, and <span class="math inline">\(n\)</span> is the sample size.</p>
<hr>
</section>
</section>
<section id="data" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Data</h1>
<section id="stock-selection" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="stock-selection"><span class="header-section-number">3.1</span> Stock Selection</h2>
<p>Following Salami (2024), this study examines nine stocks from three sectors:</p>
<ul>
<li><strong>Financial Sector</strong>: Bank of America (BAC), JPMorgan Chase (JPM), Wells Fargo (WFC)</li>
<li><strong>Healthcare Sector</strong>: Merck (MRK), Pfizer (PFE), UnitedHealth (UNH)</li>
<li><strong>Technology Sector</strong>: Apple (AAPL), Microsoft (MSFT), NVIDIA (NVDA)</li>
</ul>
<p>This selection ensures sector diversification while focusing on large-cap, highly liquid stocks with active options markets.</p>
</section>
<section id="data-sources" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="data-sources"><span class="header-section-number">3.2</span> Data Sources</h2>
<ul>
<li><strong>Stock Prices</strong>: Yahoo Finance</li>
<li><strong>Option Chains</strong>: Yahoo Finance</li>
<li><strong>Risk-Free Rate</strong>: U.S. Federal Reserve (3-month Treasury rate)</li>
</ul>
<p>The study period covers one month of trading data to capture recent market conditions.</p>
<div id="load-data" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># =============================================================================</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># DATA LOADING</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># =============================================================================</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>DATA_DIR <span class="op">=</span> <span class="st">'data'</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> generate_sample_data():</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Generate sample data for demonstration when real data is unavailable."""</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    stocks <span class="op">=</span> {</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">'BAC'</span>: {<span class="st">'name'</span>: <span class="st">'Bank of America'</span>, <span class="st">'sector'</span>: <span class="st">'Financial'</span>, <span class="st">'spot'</span>: <span class="fl">37.50</span>, <span class="st">'div'</span>: <span class="fl">0.026</span>},</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">'JPM'</span>: {<span class="st">'name'</span>: <span class="st">'JPMorgan Chase'</span>, <span class="st">'sector'</span>: <span class="st">'Financial'</span>, <span class="st">'spot'</span>: <span class="fl">195.80</span>, <span class="st">'div'</span>: <span class="fl">0.023</span>},</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">'WFC'</span>: {<span class="st">'name'</span>: <span class="st">'Wells Fargo'</span>, <span class="st">'sector'</span>: <span class="st">'Financial'</span>, <span class="st">'spot'</span>: <span class="fl">58.20</span>, <span class="st">'div'</span>: <span class="fl">0.028</span>},</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">'MRK'</span>: {<span class="st">'name'</span>: <span class="st">'Merck &amp; Co.'</span>, <span class="st">'sector'</span>: <span class="st">'Healthcare'</span>, <span class="st">'spot'</span>: <span class="fl">105.40</span>, <span class="st">'div'</span>: <span class="fl">0.027</span>},</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">'PFE'</span>: {<span class="st">'name'</span>: <span class="st">'Pfizer Inc.'</span>, <span class="st">'sector'</span>: <span class="st">'Healthcare'</span>, <span class="st">'spot'</span>: <span class="fl">27.30</span>, <span class="st">'div'</span>: <span class="fl">0.058</span>},</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">'UNH'</span>: {<span class="st">'name'</span>: <span class="st">'UnitedHealth'</span>, <span class="st">'sector'</span>: <span class="st">'Healthcare'</span>, <span class="st">'spot'</span>: <span class="fl">520.60</span>, <span class="st">'div'</span>: <span class="fl">0.014</span>},</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>        <span class="st">'AAPL'</span>: {<span class="st">'name'</span>: <span class="st">'Apple Inc.'</span>, <span class="st">'sector'</span>: <span class="st">'Technology'</span>, <span class="st">'spot'</span>: <span class="fl">185.50</span>, <span class="st">'div'</span>: <span class="fl">0.005</span>},</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>        <span class="st">'MSFT'</span>: {<span class="st">'name'</span>: <span class="st">'Microsoft'</span>, <span class="st">'sector'</span>: <span class="st">'Technology'</span>, <span class="st">'spot'</span>: <span class="fl">420.30</span>, <span class="st">'div'</span>: <span class="fl">0.007</span>},</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>        <span class="st">'NVDA'</span>: {<span class="st">'name'</span>: <span class="st">'NVIDIA'</span>, <span class="st">'sector'</span>: <span class="st">'Technology'</span>, <span class="st">'spot'</span>: <span class="fl">875.40</span>, <span class="st">'div'</span>: <span class="fl">0.000</span>}</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    dates <span class="op">=</span> pd.date_range(end<span class="op">=</span>datetime.now(), periods<span class="op">=</span><span class="dv">22</span>, freq<span class="op">=</span><span class="st">'B'</span>)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    history_data <span class="op">=</span> []</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> ticker, info <span class="kw">in</span> stocks.items():</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>        np.random.seed(<span class="bu">hash</span>(ticker) <span class="op">%</span> <span class="dv">2</span><span class="op">**</span><span class="dv">32</span>)</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>        base_price <span class="op">=</span> info[<span class="st">'spot'</span>]</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>        returns <span class="op">=</span> np.random.normal(<span class="fl">0.0005</span>, <span class="fl">0.015</span>, <span class="bu">len</span>(dates))</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>        prices <span class="op">=</span> base_price <span class="op">*</span> np.exp(np.cumsum(returns))</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i, date <span class="kw">in</span> <span class="bu">enumerate</span>(dates):</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>            history_data.append({</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>                <span class="st">'date'</span>: date, <span class="st">'ticker'</span>: ticker, <span class="st">'close'</span>: prices[i]</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>            })</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>    stock_history <span class="op">=</span> pd.DataFrame(history_data)</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>    stock_info <span class="op">=</span> pd.DataFrame([</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>        {<span class="st">'ticker'</span>: k, <span class="st">'name'</span>: v[<span class="st">'name'</span>], <span class="st">'sector'</span>: v[<span class="st">'sector'</span>], </span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>         <span class="st">'spot_price'</span>: v[<span class="st">'spot'</span>], <span class="st">'dividend_yield'</span>: v[<span class="st">'div'</span>]}</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> k, v <span class="kw">in</span> stocks.items()</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>    risk_free_rate <span class="op">=</span> <span class="fl">0.045</span></span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>    T <span class="op">=</span> <span class="dv">35</span> <span class="op">/</span> <span class="dv">365</span></span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> bs_price(S, K, T, r, sigma, delta, opt_type):</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>        d1 <span class="op">=</span> (np.log(S<span class="op">/</span>K) <span class="op">+</span> (r <span class="op">-</span> delta <span class="op">+</span> <span class="fl">0.5</span><span class="op">*</span>sigma<span class="op">**</span><span class="dv">2</span>)<span class="op">*</span>T) <span class="op">/</span> (sigma<span class="op">*</span>np.sqrt(T))</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>        d2 <span class="op">=</span> d1 <span class="op">-</span> sigma<span class="op">*</span>np.sqrt(T)</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> opt_type <span class="op">==</span> <span class="st">'call'</span>:</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> S<span class="op">*</span>np.exp(<span class="op">-</span>delta<span class="op">*</span>T)<span class="op">*</span>norm.cdf(d1) <span class="op">-</span> K<span class="op">*</span>np.exp(<span class="op">-</span>r<span class="op">*</span>T)<span class="op">*</span>norm.cdf(d2)</span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> K<span class="op">*</span>np.exp(<span class="op">-</span>r<span class="op">*</span>T)<span class="op">*</span>norm.cdf(<span class="op">-</span>d2) <span class="op">-</span> S<span class="op">*</span>np.exp(<span class="op">-</span>delta<span class="op">*</span>T)<span class="op">*</span>norm.cdf(<span class="op">-</span>d1)</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>    calls_data, puts_data <span class="op">=</span> [], []</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> ticker, info <span class="kw">in</span> stocks.items():</span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a>        np.random.seed(<span class="bu">hash</span>(ticker <span class="op">+</span> <span class="st">'opt'</span>) <span class="op">%</span> <span class="dv">2</span><span class="op">**</span><span class="dv">32</span>)</span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a>        S <span class="op">=</span> info[<span class="st">'spot'</span>]</span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>        delta <span class="op">=</span> info[<span class="st">'div'</span>]</span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> info[<span class="st">'sector'</span>] <span class="op">==</span> <span class="st">'Technology'</span>:</span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a>            base_vol <span class="op">=</span> <span class="fl">0.35</span></span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a>        <span class="cf">elif</span> info[<span class="st">'sector'</span>] <span class="op">==</span> <span class="st">'Healthcare'</span>:</span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a>            base_vol <span class="op">=</span> <span class="fl">0.25</span></span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a>            base_vol <span class="op">=</span> <span class="fl">0.22</span></span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a>        atm <span class="op">=</span> <span class="bu">round</span>(S <span class="op">/</span> <span class="dv">5</span>) <span class="op">*</span> <span class="dv">5</span></span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a>        strikes <span class="op">=</span> np.arange(atm <span class="op">-</span> <span class="dv">20</span>, atm <span class="op">+</span> <span class="dv">25</span>, <span class="dv">5</span>)</span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> K <span class="kw">in</span> strikes:</span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a>            moneyness <span class="op">=</span> K <span class="op">/</span> S</span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a>            sigma <span class="op">=</span> base_vol <span class="op">*</span> (<span class="dv">1</span> <span class="op">+</span> <span class="fl">0.1</span> <span class="op">*</span> (moneyness <span class="op">-</span> <span class="dv">1</span>)<span class="op">**</span><span class="dv">2</span>) <span class="op">+</span> np.random.normal(<span class="dv">0</span>, <span class="fl">0.01</span>)</span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a>            sigma <span class="op">=</span> <span class="bu">max</span>(<span class="fl">0.10</span>, <span class="bu">min</span>(<span class="fl">0.80</span>, sigma))</span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a>            call_theo <span class="op">=</span> bs_price(S, K, T, risk_free_rate, sigma, delta, <span class="st">'call'</span>)</span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a>            put_theo <span class="op">=</span> bs_price(S, K, T, risk_free_rate, sigma, delta, <span class="st">'put'</span>)</span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a>            call_market <span class="op">=</span> <span class="bu">max</span>(<span class="fl">0.01</span>, call_theo <span class="op">*</span> (<span class="dv">1</span> <span class="op">+</span> np.random.normal(<span class="dv">0</span>, <span class="fl">0.02</span>)))</span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a>            put_market <span class="op">=</span> <span class="bu">max</span>(<span class="fl">0.01</span>, put_theo <span class="op">*</span> (<span class="dv">1</span> <span class="op">+</span> np.random.normal(<span class="dv">0</span>, <span class="fl">0.02</span>)))</span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a>            vol <span class="op">=</span> <span class="bu">int</span>(np.random.exponential(<span class="dv">500</span>) <span class="op">*</span> np.exp(<span class="op">-</span><span class="dv">2</span><span class="op">*</span>(moneyness<span class="op">-</span><span class="dv">1</span>)<span class="op">**</span><span class="dv">2</span>) <span class="op">+</span> <span class="dv">50</span>)</span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a>            calls_data.append({</span>
<span id="cb2-86"><a href="#cb2-86" aria-hidden="true" tabindex="-1"></a>                <span class="st">'ticker'</span>: ticker, <span class="st">'strike'</span>: K, <span class="st">'lastPrice'</span>: <span class="bu">round</span>(call_market, <span class="dv">2</span>),</span>
<span id="cb2-87"><a href="#cb2-87" aria-hidden="true" tabindex="-1"></a>                <span class="st">'impliedVolatility'</span>: sigma, <span class="st">'volume'</span>: vol, <span class="st">'T'</span>: T, <span class="st">'days_to_expiry'</span>: <span class="dv">35</span></span>
<span id="cb2-88"><a href="#cb2-88" aria-hidden="true" tabindex="-1"></a>            })</span>
<span id="cb2-89"><a href="#cb2-89" aria-hidden="true" tabindex="-1"></a>            puts_data.append({</span>
<span id="cb2-90"><a href="#cb2-90" aria-hidden="true" tabindex="-1"></a>                <span class="st">'ticker'</span>: ticker, <span class="st">'strike'</span>: K, <span class="st">'lastPrice'</span>: <span class="bu">round</span>(put_market, <span class="dv">2</span>),</span>
<span id="cb2-91"><a href="#cb2-91" aria-hidden="true" tabindex="-1"></a>                <span class="st">'impliedVolatility'</span>: sigma, <span class="st">'volume'</span>: vol, <span class="st">'T'</span>: T, <span class="st">'days_to_expiry'</span>: <span class="dv">35</span></span>
<span id="cb2-92"><a href="#cb2-92" aria-hidden="true" tabindex="-1"></a>            })</span>
<span id="cb2-93"><a href="#cb2-93" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-94"><a href="#cb2-94" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> stock_history, stock_info, pd.DataFrame(calls_data), pd.DataFrame(puts_data), risk_free_rate</span>
<span id="cb2-95"><a href="#cb2-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-96"><a href="#cb2-96" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb2-97"><a href="#cb2-97" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb2-98"><a href="#cb2-98" aria-hidden="true" tabindex="-1"></a>    stock_history <span class="op">=</span> pd.read_csv(<span class="ss">f'</span><span class="sc">{</span>DATA_DIR<span class="sc">}</span><span class="ss">/stock_history.csv'</span>, parse_dates<span class="op">=</span>[<span class="st">'date'</span>])</span>
<span id="cb2-99"><a href="#cb2-99" aria-hidden="true" tabindex="-1"></a>    stock_info <span class="op">=</span> pd.read_csv(<span class="ss">f'</span><span class="sc">{</span>DATA_DIR<span class="sc">}</span><span class="ss">/stock_info.csv'</span>)</span>
<span id="cb2-100"><a href="#cb2-100" aria-hidden="true" tabindex="-1"></a>    calls_df <span class="op">=</span> pd.read_csv(<span class="ss">f'</span><span class="sc">{</span>DATA_DIR<span class="sc">}</span><span class="ss">/options_calls.csv'</span>)</span>
<span id="cb2-101"><a href="#cb2-101" aria-hidden="true" tabindex="-1"></a>    puts_df <span class="op">=</span> pd.read_csv(<span class="ss">f'</span><span class="sc">{</span>DATA_DIR<span class="sc">}</span><span class="ss">/options_puts.csv'</span>)</span>
<span id="cb2-102"><a href="#cb2-102" aria-hidden="true" tabindex="-1"></a>    risk_free_df <span class="op">=</span> pd.read_csv(<span class="ss">f'</span><span class="sc">{</span>DATA_DIR<span class="sc">}</span><span class="ss">/risk_free_rate.csv'</span>)</span>
<span id="cb2-103"><a href="#cb2-103" aria-hidden="true" tabindex="-1"></a>    risk_free_rate <span class="op">=</span> risk_free_df[<span class="st">'rate'</span>].iloc[<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb2-104"><a href="#cb2-104" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"✓ Loaded real market data from CSV files"</span>)</span>
<span id="cb2-105"><a href="#cb2-105" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span>:</span>
<span id="cb2-106"><a href="#cb2-106" aria-hidden="true" tabindex="-1"></a>    stock_history, stock_info, calls_df, puts_df, risk_free_rate <span class="op">=</span> generate_sample_data()</span>
<span id="cb2-107"><a href="#cb2-107" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"✓ Using generated sample data for demonstration"</span>)</span>
<span id="cb2-108"><a href="#cb2-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-109"><a href="#cb2-109" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Data Summary:"</span>)</span>
<span id="cb2-110"><a href="#cb2-110" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Stocks: </span><span class="sc">{</span>stock_info[<span class="st">'ticker'</span>]<span class="sc">.</span>nunique()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-111"><a href="#cb2-111" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Call Options: </span><span class="sc">{</span><span class="bu">len</span>(calls_df)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-112"><a href="#cb2-112" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Put Options: </span><span class="sc">{</span><span class="bu">len</span>(puts_df)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-113"><a href="#cb2-113" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Risk-Free Rate: </span><span class="sc">{</span>risk_free_rate<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>✓ Loaded real market data from CSV files

Data Summary:
  Stocks: 9
  Call Options: 308
  Put Options: 245
  Risk-Free Rate: 4.50%</code></pre>
</div>
</div>
<div id="display-stocks" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Selected Stocks:"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>display_df <span class="op">=</span> stock_info[[<span class="st">'ticker'</span>, <span class="st">'name'</span>, <span class="st">'sector'</span>, <span class="st">'spot_price'</span>, <span class="st">'dividend_yield'</span>]].copy()</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>display_df[<span class="st">'spot_price'</span>] <span class="op">=</span> display_df[<span class="st">'spot_price'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="ss">f"$</span><span class="sc">{</span>x<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>display_df[<span class="st">'dividend_yield'</span>] <span class="op">=</span> display_df[<span class="st">'dividend_yield'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>display_df.columns <span class="op">=</span> [<span class="st">'Ticker'</span>, <span class="st">'Company Name'</span>, <span class="st">'Sector'</span>, <span class="st">'Spot Price'</span>, <span class="st">'Dividend Yield'</span>]</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(display_df.to_string(index<span class="op">=</span><span class="va">False</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Selected Stocks:
======================================================================
Ticker                Company Name     Sector Spot Price Dividend Yield
   BAC Bank of America Corporation  Financial     $52.02        215.00%
   JPM        JPMorgan Chase &amp; Co.  Financial    $301.04        199.00%
   WFC       Wells Fargo &amp; Company  Financial     $88.05        204.00%
   MRK        Merck &amp; Company Inc. Healthcare    $107.40        317.00%
   PFE                 Pfizer Inc. Healthcare     $25.88        665.00%
   UNH     UnitedHealth Group Inc. Healthcare    $351.64        251.00%
  AAPL                  Apple Inc. Technology    $255.41         41.00%
  MSFT       Microsoft Corporation Technology    $470.28         77.00%
  NVDA          NVIDIA Corporation Technology    $186.47          2.00%</code></pre>
</div>
</div>
<hr>
</section>
</section>
<section id="empirical-results" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Empirical Results</h1>
<section id="stock-price-trend-analysis" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="stock-price-trend-analysis"><span class="header-section-number">4.1</span> Stock Price Trend Analysis</h2>
<div id="cell-fig-stock-trends" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">10</span>))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>axes <span class="op">=</span> axes.flatten()</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>sectors <span class="op">=</span> {<span class="st">'Financial'</span>: [<span class="st">'BAC'</span>, <span class="st">'JPM'</span>, <span class="st">'WFC'</span>],</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>           <span class="st">'Healthcare'</span>: [<span class="st">'MRK'</span>, <span class="st">'PFE'</span>, <span class="st">'UNH'</span>],</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>           <span class="st">'Technology'</span>: [<span class="st">'AAPL'</span>, <span class="st">'MSFT'</span>, <span class="st">'NVDA'</span>]}</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> {<span class="st">'Financial'</span>: <span class="st">'#2E86AB'</span>, <span class="st">'Healthcare'</span>: <span class="st">'#A23B72'</span>, <span class="st">'Technology'</span>: <span class="st">'#F18F01'</span>}</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, ticker <span class="kw">in</span> <span class="bu">enumerate</span>(stock_info[<span class="st">'ticker'</span>]):</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> axes[i]</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> stock_history[stock_history[<span class="st">'ticker'</span>] <span class="op">==</span> ticker].copy()</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    sector <span class="op">=</span> stock_info[stock_info[<span class="st">'ticker'</span>] <span class="op">==</span> ticker][<span class="st">'sector'</span>].values[<span class="dv">0</span>]</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    ax.plot(data[<span class="st">'date'</span>], data[<span class="st">'close'</span>], color<span class="op">=</span>colors[sector], linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    ax.fill_between(data[<span class="st">'date'</span>], data[<span class="st">'close'</span>].<span class="bu">min</span>() <span class="op">*</span> <span class="fl">0.98</span>, data[<span class="st">'close'</span>], </span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>                    alpha<span class="op">=</span><span class="fl">0.3</span>, color<span class="op">=</span>colors[sector])</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f"</span><span class="sc">{</span>ticker<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span>sector<span class="sc">}</span><span class="ss">)"</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">''</span>)</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>    ax.tick_params(axis<span class="op">=</span><span class="st">'x'</span>, rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    pct_change <span class="op">=</span> (data[<span class="st">'close'</span>].iloc[<span class="op">-</span><span class="dv">1</span>] <span class="op">/</span> data[<span class="st">'close'</span>].iloc[<span class="dv">0</span>] <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    ax.annotate(<span class="ss">f"</span><span class="sc">{</span>pct_change<span class="sc">:+.1f}</span><span class="ss">%"</span>, xy<span class="op">=</span>(<span class="fl">0.95</span>, <span class="fl">0.95</span>), xycoords<span class="op">=</span><span class="st">'axes fraction'</span>,</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>                ha<span class="op">=</span><span class="st">'right'</span>, va<span class="op">=</span><span class="st">'top'</span>, fontsize<span class="op">=</span><span class="dv">10</span>, </span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span><span class="st">'green'</span> <span class="cf">if</span> pct_change <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> <span class="st">'red'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">'Stock Price Trends During Study Period'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>, y<span class="op">=</span><span class="fl">1.02</span>)</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-stock-trends" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stock-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pde3_files/figure-html/fig-stock-trends-output-1.png" width="1326" height="983" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stock-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Stock Price Trends During Study Period
</figcaption>
</figure>
</div>
</div>
</div>
<section id="interpretation-stock-price-trends" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="interpretation-stock-price-trends"><span class="header-section-number">4.1.1</span> Interpretation: Stock Price Trends</h3>
<p>The stock price trend analysis reveals the market conditions during our study period. Key observations include:</p>
<ol type="1">
<li><p><strong>Volatility Differences by Sector</strong>: Technology stocks (AAPL, MSFT, NVDA) generally exhibit higher price volatility compared to Financial (BAC, JPM, WFC) and Healthcare (MRK, PFE, UNH) stocks. This higher volatility in technology stocks directly impacts option pricing, as volatility is a key input to the Black-Scholes model.</p></li>
<li><p><strong>Market Direction</strong>: The percentage changes shown in each chart indicate whether the stock was in an uptrend or downtrend during the study period. Stocks experiencing significant price movements may show larger pricing discrepancies between market and theoretical option prices.</p></li>
<li><p><strong>Implications for Option Pricing</strong>: During periods of high volatility or rapid price changes, the Black-Scholes assumption of constant volatility becomes less valid, potentially leading to larger pricing errors.</p></li>
</ol>
<hr>
</section>
</section>
<section id="blackscholes-model-implementation-and-pricing" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="blackscholes-model-implementation-and-pricing"><span class="header-section-number">4.2</span> Black–Scholes Model Implementation and Pricing</h2>
<div id="bs-model" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> BlackScholesModel:</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Extended Black-Scholes model with dividend yield."""</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, S, K, T, r, sigma, delta<span class="op">=</span><span class="dv">0</span>):</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.S, <span class="va">self</span>.K, <span class="va">self</span>.T, <span class="va">self</span>.r, <span class="va">self</span>.sigma, <span class="va">self</span>.delta <span class="op">=</span> S, K, T, r, sigma, delta</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>._compute_d()</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> _compute_d(<span class="va">self</span>):</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="va">self</span>.T <span class="op">&lt;=</span> <span class="dv">0</span> <span class="kw">or</span> <span class="va">self</span>.sigma <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>            <span class="va">self</span>.d1 <span class="op">=</span> <span class="va">self</span>.d2 <span class="op">=</span> np.nan</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>            <span class="va">self</span>.d1 <span class="op">=</span> (np.log(<span class="va">self</span>.S<span class="op">/</span><span class="va">self</span>.K) <span class="op">+</span> (<span class="va">self</span>.r <span class="op">-</span> <span class="va">self</span>.delta <span class="op">+</span> <span class="fl">0.5</span><span class="op">*</span><span class="va">self</span>.sigma<span class="op">**</span><span class="dv">2</span>)<span class="op">*</span><span class="va">self</span>.T) <span class="op">/</span> (<span class="va">self</span>.sigma<span class="op">*</span>np.sqrt(<span class="va">self</span>.T))</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>            <span class="va">self</span>.d2 <span class="op">=</span> <span class="va">self</span>.d1 <span class="op">-</span> <span class="va">self</span>.sigma<span class="op">*</span>np.sqrt(<span class="va">self</span>.T)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> call_price(<span class="va">self</span>):</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="va">self</span>.T <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="bu">max</span>(<span class="va">self</span>.S <span class="op">-</span> <span class="va">self</span>.K, <span class="dv">0</span>)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.S <span class="op">*</span> np.exp(<span class="op">-</span><span class="va">self</span>.delta<span class="op">*</span><span class="va">self</span>.T) <span class="op">*</span> norm.cdf(<span class="va">self</span>.d1) <span class="op">-</span> <span class="va">self</span>.K <span class="op">*</span> np.exp(<span class="op">-</span><span class="va">self</span>.r<span class="op">*</span><span class="va">self</span>.T) <span class="op">*</span> norm.cdf(<span class="va">self</span>.d2)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> put_price(<span class="va">self</span>):</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="va">self</span>.T <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="bu">max</span>(<span class="va">self</span>.K <span class="op">-</span> <span class="va">self</span>.S, <span class="dv">0</span>)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.K <span class="op">*</span> np.exp(<span class="op">-</span><span class="va">self</span>.r<span class="op">*</span><span class="va">self</span>.T) <span class="op">*</span> norm.cdf(<span class="op">-</span><span class="va">self</span>.d2) <span class="op">-</span> <span class="va">self</span>.S <span class="op">*</span> np.exp(<span class="op">-</span><span class="va">self</span>.delta<span class="op">*</span><span class="va">self</span>.T) <span class="op">*</span> norm.cdf(<span class="op">-</span><span class="va">self</span>.d1)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> compute_bs_prices(calls_df, puts_df, stock_info, risk_free_rate):</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Compute Black-Scholes theoretical prices for all options."""</span></span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>    calls_results, puts_results <span class="op">=</span> [], []</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _, row <span class="kw">in</span> calls_df.iterrows():</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>        ticker <span class="op">=</span> row[<span class="st">'ticker'</span>]</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>        stock <span class="op">=</span> stock_info[stock_info[<span class="st">'ticker'</span>] <span class="op">==</span> ticker].iloc[<span class="dv">0</span>]</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>        S, K <span class="op">=</span> stock[<span class="st">'spot_price'</span>], row[<span class="st">'strike'</span>]</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>        T <span class="op">=</span> row[<span class="st">'T'</span>] <span class="cf">if</span> <span class="st">'T'</span> <span class="kw">in</span> row <span class="cf">else</span> row[<span class="st">'days_to_expiry'</span>] <span class="op">/</span> <span class="dv">365</span></span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>        delta, sigma <span class="op">=</span> stock[<span class="st">'dividend_yield'</span>], row[<span class="st">'impliedVolatility'</span>]</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>        market_price <span class="op">=</span> row[<span class="st">'lastPrice'</span>]</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>        bs <span class="op">=</span> BlackScholesModel(S, K, T, risk_free_rate, sigma, delta)</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>        bs_price <span class="op">=</span> bs.call_price()</span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>        calls_results.append({</span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>            <span class="st">'ticker'</span>: ticker, <span class="st">'strike'</span>: K, <span class="st">'T'</span>: T,</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>            <span class="st">'market_price'</span>: market_price, <span class="st">'bs_price'</span>: bs_price,</span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>            <span class="st">'error'</span>: market_price <span class="op">-</span> bs_price,</span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a>            <span class="st">'pct_error'</span>: (market_price <span class="op">-</span> bs_price) <span class="op">/</span> market_price <span class="op">*</span> <span class="dv">100</span> <span class="cf">if</span> market_price <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> np.nan,</span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a>            <span class="st">'sigma'</span>: sigma</span>
<span id="cb7-48"><a href="#cb7-48" aria-hidden="true" tabindex="-1"></a>        })</span>
<span id="cb7-49"><a href="#cb7-49" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-50"><a href="#cb7-50" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _, row <span class="kw">in</span> puts_df.iterrows():</span>
<span id="cb7-51"><a href="#cb7-51" aria-hidden="true" tabindex="-1"></a>        ticker <span class="op">=</span> row[<span class="st">'ticker'</span>]</span>
<span id="cb7-52"><a href="#cb7-52" aria-hidden="true" tabindex="-1"></a>        stock <span class="op">=</span> stock_info[stock_info[<span class="st">'ticker'</span>] <span class="op">==</span> ticker].iloc[<span class="dv">0</span>]</span>
<span id="cb7-53"><a href="#cb7-53" aria-hidden="true" tabindex="-1"></a>        S, K <span class="op">=</span> stock[<span class="st">'spot_price'</span>], row[<span class="st">'strike'</span>]</span>
<span id="cb7-54"><a href="#cb7-54" aria-hidden="true" tabindex="-1"></a>        T <span class="op">=</span> row[<span class="st">'T'</span>] <span class="cf">if</span> <span class="st">'T'</span> <span class="kw">in</span> row <span class="cf">else</span> row[<span class="st">'days_to_expiry'</span>] <span class="op">/</span> <span class="dv">365</span></span>
<span id="cb7-55"><a href="#cb7-55" aria-hidden="true" tabindex="-1"></a>        delta, sigma <span class="op">=</span> stock[<span class="st">'dividend_yield'</span>], row[<span class="st">'impliedVolatility'</span>]</span>
<span id="cb7-56"><a href="#cb7-56" aria-hidden="true" tabindex="-1"></a>        market_price <span class="op">=</span> row[<span class="st">'lastPrice'</span>]</span>
<span id="cb7-57"><a href="#cb7-57" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb7-58"><a href="#cb7-58" aria-hidden="true" tabindex="-1"></a>        bs <span class="op">=</span> BlackScholesModel(S, K, T, risk_free_rate, sigma, delta)</span>
<span id="cb7-59"><a href="#cb7-59" aria-hidden="true" tabindex="-1"></a>        bs_price <span class="op">=</span> bs.put_price()</span>
<span id="cb7-60"><a href="#cb7-60" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb7-61"><a href="#cb7-61" aria-hidden="true" tabindex="-1"></a>        puts_results.append({</span>
<span id="cb7-62"><a href="#cb7-62" aria-hidden="true" tabindex="-1"></a>            <span class="st">'ticker'</span>: ticker, <span class="st">'strike'</span>: K, <span class="st">'T'</span>: T,</span>
<span id="cb7-63"><a href="#cb7-63" aria-hidden="true" tabindex="-1"></a>            <span class="st">'market_price'</span>: market_price, <span class="st">'bs_price'</span>: bs_price,</span>
<span id="cb7-64"><a href="#cb7-64" aria-hidden="true" tabindex="-1"></a>            <span class="st">'error'</span>: market_price <span class="op">-</span> bs_price,</span>
<span id="cb7-65"><a href="#cb7-65" aria-hidden="true" tabindex="-1"></a>            <span class="st">'pct_error'</span>: (market_price <span class="op">-</span> bs_price) <span class="op">/</span> market_price <span class="op">*</span> <span class="dv">100</span> <span class="cf">if</span> market_price <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> np.nan,</span>
<span id="cb7-66"><a href="#cb7-66" aria-hidden="true" tabindex="-1"></a>            <span class="st">'sigma'</span>: sigma</span>
<span id="cb7-67"><a href="#cb7-67" aria-hidden="true" tabindex="-1"></a>        })</span>
<span id="cb7-68"><a href="#cb7-68" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-69"><a href="#cb7-69" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pd.DataFrame(calls_results), pd.DataFrame(puts_results)</span>
<span id="cb7-70"><a href="#cb7-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-71"><a href="#cb7-71" aria-hidden="true" tabindex="-1"></a>calls_results, puts_results <span class="op">=</span> compute_bs_prices(calls_df, puts_df, stock_info, risk_free_rate)</span>
<span id="cb7-72"><a href="#cb7-72" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Computed Black-Scholes prices for </span><span class="sc">{</span><span class="bu">len</span>(calls_results)<span class="sc">}</span><span class="ss"> calls and </span><span class="sc">{</span><span class="bu">len</span>(puts_results)<span class="sc">}</span><span class="ss"> puts"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Computed Black-Scholes prices for 308 calls and 245 puts</code></pre>
</div>
</div>
<hr>
</section>
<section id="paired-sample-t-test-results" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="paired-sample-t-test-results"><span class="header-section-number">4.3</span> Paired Sample T-Test Results</h2>
<section id="call-options" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="call-options"><span class="header-section-number">4.3.1</span> Call Options</h3>
<div id="ttest-calls" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> perform_ttest(results_df, option_type):</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Perform paired t-test for each stock."""</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    test_results <span class="op">=</span> []</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> ticker <span class="kw">in</span> results_df[<span class="st">'ticker'</span>].unique():</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        data <span class="op">=</span> results_df[results_df[<span class="st">'ticker'</span>] <span class="op">==</span> ticker]</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="bu">len</span>(data) <span class="op">&lt;</span> <span class="dv">2</span>:</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>        market <span class="op">=</span> data[<span class="st">'market_price'</span>].values</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>        bs <span class="op">=</span> data[<span class="st">'bs_price'</span>].values</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>        t_stat, p_value <span class="op">=</span> ttest_rel(market, bs)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>        mean_diff <span class="op">=</span> np.mean(market <span class="op">-</span> bs)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>        std_diff <span class="op">=</span> np.std(market <span class="op">-</span> bs, ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>        test_results.append({</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>            <span class="st">'ticker'</span>: ticker, <span class="st">'n'</span>: <span class="bu">len</span>(data),</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>            <span class="st">'mean_market'</span>: np.mean(market), <span class="st">'mean_bs'</span>: np.mean(bs),</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>            <span class="st">'mean_diff'</span>: mean_diff, <span class="st">'std_diff'</span>: std_diff,</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>            <span class="st">'t_stat'</span>: t_stat, <span class="st">'p_value'</span>: p_value,</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>            <span class="st">'significant'</span>: <span class="st">'Yes'</span> <span class="cf">if</span> p_value <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="cf">else</span> <span class="st">'No'</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>        })</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pd.DataFrame(test_results)</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>calls_ttest <span class="op">=</span> perform_ttest(calls_results, <span class="st">'call'</span>)</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">80</span>)</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"PAIRED SAMPLE T-TEST RESULTS: CALL OPTIONS"</span>)</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">80</span>)</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">H₀: No significant difference between market premium and Black-Scholes premium"</span>)</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"H₁: Significant difference exists"</span>)</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Significance level: α = 0.05</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>display_calls <span class="op">=</span> calls_ttest[[<span class="st">'ticker'</span>, <span class="st">'n'</span>, <span class="st">'mean_diff'</span>, <span class="st">'std_diff'</span>, <span class="st">'t_stat'</span>, <span class="st">'p_value'</span>, <span class="st">'significant'</span>]].copy()</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>display_calls.columns <span class="op">=</span> [<span class="st">'Ticker'</span>, <span class="st">'N'</span>, <span class="st">'Mean Diff'</span>, <span class="st">'Std Diff'</span>, <span class="st">'t-Statistic'</span>, <span class="st">'p-Value'</span>, <span class="st">'Significant?'</span>]</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(display_calls.to_string(index<span class="op">=</span><span class="va">False</span>, float_format<span class="op">=</span><span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.4f}</span><span class="ss">"</span>))</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>sig_count_calls <span class="op">=</span> (calls_ttest[<span class="st">'significant'</span>] <span class="op">==</span> <span class="st">'Yes'</span>).<span class="bu">sum</span>()</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">→ Significant difference found in </span><span class="sc">{</span>sig_count_calls<span class="sc">}</span><span class="ss"> out of </span><span class="sc">{</span><span class="bu">len</span>(calls_ttest)<span class="sc">}</span><span class="ss"> stocks"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>================================================================================
PAIRED SAMPLE T-TEST RESULTS: CALL OPTIONS
================================================================================

H₀: No significant difference between market premium and Black-Scholes premium
H₁: Significant difference exists
Significance level: α = 0.05

Ticker  N  Mean Diff  Std Diff  t-Statistic  p-Value Significant?
   BAC 25     2.2828    3.2559       3.5056   0.0018          Yes
   JPM 24    15.9999   20.1270       3.8944   0.0007          Yes
   WFC 27     1.9030    2.6491       3.7326   0.0009          Yes
   MRK 24     3.8546    3.7829       4.9918   0.0000          Yes
   PFE 20     1.5445    2.6295       2.6268   0.0166          Yes
   UNH 36    24.2555   23.2969       6.2469   0.0000          Yes
  AAPL 39     3.4580    4.5434       4.7530   0.0000          Yes
  MSFT 60    12.7133   13.6605       7.2089   0.0000          Yes
  NVDA 53     1.2167    2.5425       3.4838   0.0010          Yes

→ Significant difference found in 9 out of 9 stocks</code></pre>
</div>
</div>
</section>
<section id="put-options" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="put-options"><span class="header-section-number">4.3.2</span> Put Options</h3>
<div id="ttest-puts" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>puts_ttest <span class="op">=</span> perform_ttest(puts_results, <span class="st">'put'</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">80</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"PAIRED SAMPLE T-TEST RESULTS: PUT OPTIONS"</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">80</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">H₀: No significant difference between market premium and Black-Scholes premium"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"H₁: Significant difference exists"</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Significance level: α = 0.05</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>display_puts <span class="op">=</span> puts_ttest[[<span class="st">'ticker'</span>, <span class="st">'n'</span>, <span class="st">'mean_diff'</span>, <span class="st">'std_diff'</span>, <span class="st">'t_stat'</span>, <span class="st">'p_value'</span>, <span class="st">'significant'</span>]].copy()</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>display_puts.columns <span class="op">=</span> [<span class="st">'Ticker'</span>, <span class="st">'N'</span>, <span class="st">'Mean Diff'</span>, <span class="st">'Std Diff'</span>, <span class="st">'t-Statistic'</span>, <span class="st">'p-Value'</span>, <span class="st">'Significant?'</span>]</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(display_puts.to_string(index<span class="op">=</span><span class="va">False</span>, float_format<span class="op">=</span><span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.4f}</span><span class="ss">"</span>))</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>sig_count_puts <span class="op">=</span> (puts_ttest[<span class="st">'significant'</span>] <span class="op">==</span> <span class="st">'Yes'</span>).<span class="bu">sum</span>()</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">→ Significant difference found in </span><span class="sc">{</span>sig_count_puts<span class="sc">}</span><span class="ss"> out of </span><span class="sc">{</span><span class="bu">len</span>(puts_ttest)<span class="sc">}</span><span class="ss"> stocks"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>================================================================================
PAIRED SAMPLE T-TEST RESULTS: PUT OPTIONS
================================================================================

H₀: No significant difference between market premium and Black-Scholes premium
H₁: Significant difference exists
Significance level: α = 0.05

Ticker  N  Mean Diff  Std Diff  t-Statistic  p-Value Significant?
   BAC 18    -4.8613    3.3132      -6.2250   0.0000          Yes
   JPM 24   -26.7827   20.7826      -6.3134   0.0000          Yes
   WFC 21    -7.4552    4.4303      -7.7115   0.0000          Yes
   MRK 18   -18.0395    6.7052     -11.4143   0.0000          Yes
   PFE 14    -9.2155    1.5826     -21.7877   0.0000          Yes
   UNH 33   -28.8074   23.8734      -6.9318   0.0000          Yes
  AAPL 29    -0.3365    2.8228      -0.6420   0.5261           No
  MSFT 49    -6.6591   11.3721      -4.0989   0.0002          Yes
  NVDA 39     1.4137    2.4407       3.6172   0.0009          Yes

→ Significant difference found in 8 out of 9 stocks</code></pre>
</div>
</div>
</section>
<section id="results-visualization-p-values-by-stock" class="level3" data-number="4.3.3">
<h3 data-number="4.3.3" class="anchored" data-anchor-id="results-visualization-p-values-by-stock"><span class="header-section-number">4.3.3</span> Results Visualization: P-Values by Stock</h3>
<div id="cell-fig-ttest-results" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">6</span>))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Call options</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>ax1 <span class="op">=</span> axes[<span class="dv">0</span>]</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>colors_call <span class="op">=</span> [<span class="st">'#2ecc71'</span> <span class="cf">if</span> p <span class="op">&gt;</span> <span class="fl">0.05</span> <span class="cf">else</span> <span class="st">'#e74c3c'</span> <span class="cf">for</span> p <span class="kw">in</span> calls_ttest[<span class="st">'p_value'</span>]]</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>bars1 <span class="op">=</span> ax1.barh(calls_ttest[<span class="st">'ticker'</span>], calls_ttest[<span class="st">'p_value'</span>], color<span class="op">=</span>colors_call, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>ax1.axvline(x<span class="op">=</span><span class="fl">0.05</span>, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">'α = 0.05'</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>ax1.set_xlabel(<span class="st">'p-Value'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>ax1.set_title(<span class="st">'Call Options: p-Values by Stock'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>ax1.legend()</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> bar, p <span class="kw">in</span> <span class="bu">zip</span>(bars1, calls_ttest[<span class="st">'p_value'</span>]):</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    ax1.text(bar.get_width() <span class="op">+</span> <span class="fl">0.002</span>, bar.get_y() <span class="op">+</span> bar.get_height()<span class="op">/</span><span class="dv">2</span>, </span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>             <span class="ss">f'</span><span class="sc">{</span>p<span class="sc">:.4f}</span><span class="ss">'</span>, va<span class="op">=</span><span class="st">'center'</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Put options</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>ax2 <span class="op">=</span> axes[<span class="dv">1</span>]</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>colors_put <span class="op">=</span> [<span class="st">'#2ecc71'</span> <span class="cf">if</span> p <span class="op">&gt;</span> <span class="fl">0.05</span> <span class="cf">else</span> <span class="st">'#e74c3c'</span> <span class="cf">for</span> p <span class="kw">in</span> puts_ttest[<span class="st">'p_value'</span>]]</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>bars2 <span class="op">=</span> ax2.barh(puts_ttest[<span class="st">'ticker'</span>], puts_ttest[<span class="st">'p_value'</span>], color<span class="op">=</span>colors_put, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>ax2.axvline(x<span class="op">=</span><span class="fl">0.05</span>, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">'α = 0.05'</span>)</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>ax2.set_xlabel(<span class="st">'p-Value'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>ax2.set_title(<span class="st">'Put Options: p-Values by Stock'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>ax2.legend()</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> bar, p <span class="kw">in</span> <span class="bu">zip</span>(bars2, puts_ttest[<span class="st">'p_value'</span>]):</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>    ax2.text(bar.get_width() <span class="op">+</span> <span class="fl">0.002</span>, bar.get_y() <span class="op">+</span> bar.get_height()<span class="op">/</span><span class="dv">2</span>, </span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>             <span class="ss">f'</span><span class="sc">{</span>p<span class="sc">:.4f}</span><span class="ss">'</span>, va<span class="op">=</span><span class="st">'center'</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Legend: Green = Not Significant (p &gt; 0.05), Red = Significant (p &lt; 0.05)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-ttest-results" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ttest-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pde3_files/figure-html/fig-ttest-results-output-1.png" width="1327" height="563" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ttest-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Paired T-Test Results: p-Values by Stock and Option Type
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Legend: Green = Not Significant (p &gt; 0.05), Red = Significant (p &lt; 0.05)</code></pre>
</div>
</div>
</section>
<section id="interpretation-p-value-analysis" class="level3" data-number="4.3.4">
<h3 data-number="4.3.4" class="anchored" data-anchor-id="interpretation-p-value-analysis"><span class="header-section-number">4.3.4</span> Interpretation: P-Value Analysis</h3>
<p>The p-value charts provide a visual summary of the hypothesis test results for each stock:</p>
<p><strong>Call Options (Left Panel):</strong></p>
<ul>
<li>All nine stocks show p-values below the significance threshold (α = 0.05), indicated by red bars</li>
<li>This means we <strong>reject the null hypothesis</strong> for all call options</li>
<li>The Black-Scholes model shows <strong>statistically significant pricing differences</strong> from market prices for all call options analyzed</li>
<li>PFE shows the highest p-value (0.0166) among calls, but still significant</li>
<li>The remaining stocks have very small p-values (&lt; 0.002), indicating strong evidence against the null hypothesis</li>
</ul>
<p><strong>Put Options (Right Panel):</strong></p>
<ul>
<li><strong>AAPL is the only stock</strong> where we fail to reject the null hypothesis (p = 0.5261, shown in green)</li>
<li>For AAPL put options, there is no statistically significant difference between market and BS prices</li>
<li>All other stocks show significant differences (p &lt; 0.05)</li>
<li>This suggests the Black-Scholes model is <strong>not suitable for pricing put options</strong> in most cases</li>
</ul>
<p><strong>Key Finding:</strong> These results contrast with Salami (2024), who found the BS model works better for calls than puts. Our analysis shows significant mispricing for <strong>both</strong> option types, with only AAPL puts showing no significant difference.</p>
<hr>
</section>
</section>
<section id="pricing-error-analysis" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="pricing-error-analysis"><span class="header-section-number">4.4</span> Pricing Error Analysis</h2>
<section id="distribution-of-pricing-errors-by-stock" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="distribution-of-pricing-errors-by-stock"><span class="header-section-number">4.4.1</span> Distribution of Pricing Errors by Stock</h3>
<div id="cell-fig-error-distribution" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">12</span>))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>axes <span class="op">=</span> axes.flatten()</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, ticker <span class="kw">in</span> <span class="bu">enumerate</span>(stock_info[<span class="st">'ticker'</span>]):</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> axes[i]</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    call_errors <span class="op">=</span> calls_results[calls_results[<span class="st">'ticker'</span>] <span class="op">==</span> ticker][<span class="st">'error'</span>]</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    put_errors <span class="op">=</span> puts_results[puts_results[<span class="st">'ticker'</span>] <span class="op">==</span> ticker][<span class="st">'error'</span>]</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    ax.hist(call_errors, bins<span class="op">=</span><span class="dv">15</span>, alpha<span class="op">=</span><span class="fl">0.6</span>, label<span class="op">=</span><span class="st">'Calls'</span>, color<span class="op">=</span><span class="st">'#3498db'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    ax.hist(put_errors, bins<span class="op">=</span><span class="dv">15</span>, alpha<span class="op">=</span><span class="fl">0.6</span>, label<span class="op">=</span><span class="st">'Puts'</span>, color<span class="op">=</span><span class="st">'#e74c3c'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    ax.axvline(x<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    ax.axvline(x<span class="op">=</span>call_errors.mean(), color<span class="op">=</span><span class="st">'#3498db'</span>, linestyle<span class="op">=</span><span class="st">'-'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, alpha<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>    ax.axvline(x<span class="op">=</span>put_errors.mean(), color<span class="op">=</span><span class="st">'#e74c3c'</span>, linestyle<span class="op">=</span><span class="st">'-'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, alpha<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f'</span><span class="sc">{</span>ticker<span class="sc">}</span><span class="ss">'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">'Pricing Error ($)'</span>)</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>    ax.legend(fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">'Distribution of Pricing Errors (Market - BS)'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>, y<span class="op">=</span><span class="fl">1.02</span>)</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-error-distribution" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-error-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pde3_files/figure-html/fig-error-distribution-output-1.png" width="1331" height="1178" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-error-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Distribution of Pricing Errors by Stock (Market Price - BS Price)
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation-error-distribution" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="interpretation-error-distribution"><span class="header-section-number">4.4.2</span> Interpretation: Error Distribution</h3>
<p>The histograms reveal important patterns in how the Black-Scholes model deviates from market prices:</p>
<p><strong>Systematic Patterns Observed:</strong></p>
<ol type="1">
<li><p><strong>Call Options (Blue)</strong> consistently show <strong>positive mean errors</strong> (vertical blue lines to the right of zero), meaning market prices are <strong>higher</strong> than BS theoretical prices. The Black-Scholes model <strong>underprices</strong> call options.</p></li>
<li><p><strong>Put Options (Red)</strong> consistently show <strong>negative mean errors</strong> (vertical red lines to the left of zero), meaning market prices are <strong>lower</strong> than BS theoretical prices. The Black-Scholes model <strong>overprices</strong> put options.</p></li>
<li><p><strong>Stock-Specific Observations:</strong></p>
<ul>
<li><strong>JPM and UNH</strong>: Show the widest error distributions, indicating high pricing variability</li>
<li><strong>NVDA</strong>: Shows relatively tight distributions centered near zero, especially for puts</li>
<li><strong>MRK</strong>: Put errors are notably skewed negative with some extreme values</li>
</ul></li>
<li><p><strong>Implications:</strong> The systematic nature of these errors (calls underpriced, puts overpriced) suggests the model fails to capture some market dynamics, possibly related to volatility skew or risk premiums not accounted for in the BS assumptions.</p></li>
</ol>
<hr>
</section>
<section id="mean-pricing-error-by-stock" class="level3" data-number="4.4.3">
<h3 data-number="4.4.3" class="anchored" data-anchor-id="mean-pricing-error-by-stock"><span class="header-section-number">4.4.3</span> Mean Pricing Error by Stock</h3>
<div id="cell-fig-mean-errors" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">6</span>))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.arange(<span class="bu">len</span>(stock_info))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>width <span class="op">=</span> <span class="fl">0.35</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>call_means <span class="op">=</span> [calls_results[calls_results[<span class="st">'ticker'</span>] <span class="op">==</span> t][<span class="st">'error'</span>].mean() <span class="cf">for</span> t <span class="kw">in</span> stock_info[<span class="st">'ticker'</span>]]</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>put_means <span class="op">=</span> [puts_results[puts_results[<span class="st">'ticker'</span>] <span class="op">==</span> t][<span class="st">'error'</span>].mean() <span class="cf">for</span> t <span class="kw">in</span> stock_info[<span class="st">'ticker'</span>]]</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>bars1 <span class="op">=</span> ax.bar(x <span class="op">-</span> width<span class="op">/</span><span class="dv">2</span>, call_means, width, label<span class="op">=</span><span class="st">'Call Options'</span>, color<span class="op">=</span><span class="st">'#3498db'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>bars2 <span class="op">=</span> ax.bar(x <span class="op">+</span> width<span class="op">/</span><span class="dv">2</span>, put_means, width, label<span class="op">=</span><span class="st">'Put Options'</span>, color<span class="op">=</span><span class="st">'#e74c3c'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>ax.axhline(y<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'-'</span>, linewidth<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Stock'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Mean Pricing Error ($)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Mean Pricing Error by Stock (Market Price - BS Price)'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(x)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>ax.set_xticklabels(stock_info[<span class="st">'ticker'</span>])</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> bar <span class="kw">in</span> bars1:</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>    height <span class="op">=</span> bar.get_height()</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>    ax.annotate(<span class="ss">f'</span><span class="sc">{</span>height<span class="sc">:.3f}</span><span class="ss">'</span>, xy<span class="op">=</span>(bar.get_x() <span class="op">+</span> bar.get_width()<span class="op">/</span><span class="dv">2</span>, height),</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>                xytext<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">3</span> <span class="cf">if</span> height <span class="op">&gt;=</span> <span class="dv">0</span> <span class="cf">else</span> <span class="op">-</span><span class="dv">12</span>), textcoords<span class="op">=</span><span class="st">"offset points"</span>,</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>                ha<span class="op">=</span><span class="st">'center'</span>, va<span class="op">=</span><span class="st">'bottom'</span> <span class="cf">if</span> height <span class="op">&gt;=</span> <span class="dv">0</span> <span class="cf">else</span> <span class="st">'top'</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> bar <span class="kw">in</span> bars2:</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>    height <span class="op">=</span> bar.get_height()</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>    ax.annotate(<span class="ss">f'</span><span class="sc">{</span>height<span class="sc">:.3f}</span><span class="ss">'</span>, xy<span class="op">=</span>(bar.get_x() <span class="op">+</span> bar.get_width()<span class="op">/</span><span class="dv">2</span>, height),</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>                xytext<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">3</span> <span class="cf">if</span> height <span class="op">&gt;=</span> <span class="dv">0</span> <span class="cf">else</span> <span class="op">-</span><span class="dv">12</span>), textcoords<span class="op">=</span><span class="st">"offset points"</span>,</span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>                ha<span class="op">=</span><span class="st">'center'</span>, va<span class="op">=</span><span class="st">'bottom'</span> <span class="cf">if</span> height <span class="op">&gt;=</span> <span class="dv">0</span> <span class="cf">else</span> <span class="st">'top'</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-mean-errors" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mean-errors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pde3_files/figure-html/fig-mean-errors-output-1.png" width="1331" height="563" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mean-errors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Mean Pricing Errors by Stock (Market Price - BS Price)
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation-mean-pricing-errors" class="level3" data-number="4.4.4">
<h3 data-number="4.4.4" class="anchored" data-anchor-id="interpretation-mean-pricing-errors"><span class="header-section-number">4.4.4</span> Interpretation: Mean Pricing Errors</h3>
<p>This chart quantifies the average pricing discrepancy for each stock:</p>
<p><strong>Key Findings:</strong></p>
<ol type="1">
<li><strong>Consistent Directional Bias:</strong>
<ul>
<li><strong>All call options</strong> show positive mean errors (blue bars above zero)</li>
<li><strong>Most put options</strong> show negative mean errors (red bars below zero)</li>
<li>Exception: NVDA puts show a small positive mean error ($1.414)</li>
</ul></li>
<li><strong>Magnitude of Errors:</strong>
<ul>
<li><strong>UNH</strong> has the largest call option error (+$24.256) and put option error (-$28.807)</li>
<li><strong>JPM</strong> shows substantial errors: +$16.00 for calls, -$26.783 for puts</li>
<li><strong>AAPL</strong> has relatively small errors: +$3.458 for calls, -$0.337 for puts (explaining why AAPL puts passed the t-test)</li>
</ul></li>
<li><strong>Sector Patterns:</strong>
<ul>
<li><strong>Healthcare stocks (MRK, PFE, UNH)</strong>: Show large absolute errors, especially UNH</li>
<li><strong>Financial stocks (BAC, JPM, WFC)</strong>: JPM dominates with large errors</li>
<li><strong>Technology stocks</strong>: More moderate errors, with NVDA showing the smallest</li>
</ul></li>
<li><strong>Economic Significance:</strong> Even when errors are statistically significant, their dollar magnitude matters for trading decisions. A $0.34 error (AAPL puts) may be within bid-ask spreads, while a $28 error (UNH puts) represents substantial mispricing.</li>
</ol>
<hr>
</section>
<section id="standard-deviation-of-pricing-errors" class="level3" data-number="4.4.5">
<h3 data-number="4.4.5" class="anchored" data-anchor-id="standard-deviation-of-pricing-errors"><span class="header-section-number">4.4.5</span> Standard Deviation of Pricing Errors</h3>
<div id="cell-fig-std-errors" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">6</span>))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>call_stds <span class="op">=</span> [calls_results[calls_results[<span class="st">'ticker'</span>] <span class="op">==</span> t][<span class="st">'error'</span>].std() <span class="cf">for</span> t <span class="kw">in</span> stock_info[<span class="st">'ticker'</span>]]</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>put_stds <span class="op">=</span> [puts_results[puts_results[<span class="st">'ticker'</span>] <span class="op">==</span> t][<span class="st">'error'</span>].std() <span class="cf">for</span> t <span class="kw">in</span> stock_info[<span class="st">'ticker'</span>]]</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>bars1 <span class="op">=</span> ax.bar(x <span class="op">-</span> width<span class="op">/</span><span class="dv">2</span>, call_stds, width, label<span class="op">=</span><span class="st">'Call Options'</span>, color<span class="op">=</span><span class="st">'#3498db'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>bars2 <span class="op">=</span> ax.bar(x <span class="op">+</span> width<span class="op">/</span><span class="dv">2</span>, put_stds, width, label<span class="op">=</span><span class="st">'Put Options'</span>, color<span class="op">=</span><span class="st">'#e74c3c'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Stock'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Standard Deviation ($)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Standard Deviation of Pricing Errors by Stock'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(x)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>ax.set_xticklabels(stock_info[<span class="st">'ticker'</span>])</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>min_std_idx <span class="op">=</span> np.argmin(np.array(call_stds) <span class="op">+</span> np.array(put_stds))</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>max_std_idx <span class="op">=</span> np.argmax(np.array(call_stds) <span class="op">+</span> np.array(put_stds))</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Lowest fluctuation (most consistent): </span><span class="sc">{</span>stock_info[<span class="st">'ticker'</span>]<span class="sc">.</span>iloc[min_std_idx]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Highest fluctuation (most variable): </span><span class="sc">{</span>stock_info[<span class="st">'ticker'</span>]<span class="sc">.</span>iloc[max_std_idx]<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-std-errors" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-std-errors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pde3_files/figure-html/fig-std-errors-output-1.png" width="1331" height="563" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-std-errors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Standard Deviation of Pricing Errors by Stock
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Lowest fluctuation (most consistent): PFE
Highest fluctuation (most variable): UNH</code></pre>
</div>
</div>
</section>
<section id="interpretation-standard-deviation-analysis" class="level3" data-number="4.4.6">
<h3 data-number="4.4.6" class="anchored" data-anchor-id="interpretation-standard-deviation-analysis"><span class="header-section-number">4.4.6</span> Interpretation: Standard Deviation Analysis</h3>
<p>Standard deviation measures the <strong>variability</strong> or <strong>consistency</strong> of pricing errors:</p>
<p><strong>Key Observations:</strong></p>
<ol type="1">
<li><strong>Most Variable (Highest Std):</strong>
<ul>
<li><strong>UNH</strong> shows the highest standard deviation (~$23-24) for both calls and puts</li>
<li><strong>JPM</strong> also shows high variability (~$20-21)</li>
<li>High standard deviation indicates <strong>inconsistent</strong> model performance across different strike prices</li>
</ul></li>
<li><strong>Most Consistent (Lowest Std):</strong>
<ul>
<li><strong>NVDA</strong> shows the lowest standard deviation (~$2.5) for both option types</li>
<li><strong>PFE</strong> also shows relatively low variability</li>
<li>Low standard deviation suggests the model error is <strong>predictable</strong> and consistent</li>
</ul></li>
<li><strong>Stock Price Level Effect:</strong>
<ul>
<li>Higher-priced stocks (UNH ~$520, JPM ~$196) tend to have higher absolute standard deviations</li>
<li>Lower-priced stocks (PFE ~$27, BAC ~$37) have lower absolute standard deviations</li>
<li>This is expected since option premiums scale with stock price</li>
</ul></li>
<li><strong>Implications for Trading:</strong>
<ul>
<li>Stocks with low std (like NVDA) may be more suitable for BS-based trading strategies</li>
<li>Stocks with high std (like UNH) require additional risk adjustments when using BS prices</li>
</ul></li>
</ol>
<hr>
</section>
</section>
<section id="sector-analysis" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="sector-analysis"><span class="header-section-number">4.5</span> Sector Analysis</h2>
<div id="cell-fig-sector-analysis" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>calls_with_sector <span class="op">=</span> calls_results.merge(stock_info[[<span class="st">'ticker'</span>, <span class="st">'sector'</span>]], on<span class="op">=</span><span class="st">'ticker'</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>puts_with_sector <span class="op">=</span> puts_results.merge(stock_info[[<span class="st">'ticker'</span>, <span class="st">'sector'</span>]], on<span class="op">=</span><span class="st">'ticker'</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">5</span>))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>sectors <span class="op">=</span> [<span class="st">'Financial'</span>, <span class="st">'Healthcare'</span>, <span class="st">'Technology'</span>]</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>sector_colors <span class="op">=</span> [<span class="st">'#2E86AB'</span>, <span class="st">'#A23B72'</span>, <span class="st">'#F18F01'</span>]</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Call options</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>ax1 <span class="op">=</span> axes[<span class="dv">0</span>]</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>call_sector_data <span class="op">=</span> [calls_with_sector[calls_with_sector[<span class="st">'sector'</span>] <span class="op">==</span> s][<span class="st">'error'</span>] <span class="cf">for</span> s <span class="kw">in</span> sectors]</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>bp1 <span class="op">=</span> ax1.boxplot(call_sector_data, labels<span class="op">=</span>sectors, patch_artist<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> patch, color <span class="kw">in</span> <span class="bu">zip</span>(bp1[<span class="st">'boxes'</span>], sector_colors):</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    patch.set_facecolor(color)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>    patch.set_alpha(<span class="fl">0.7</span>)</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>ax1.axhline(y<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">'Pricing Error ($)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>ax1.set_title(<span class="st">'Call Options: Pricing Error by Sector'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Put options</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>ax2 <span class="op">=</span> axes[<span class="dv">1</span>]</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>put_sector_data <span class="op">=</span> [puts_with_sector[puts_with_sector[<span class="st">'sector'</span>] <span class="op">==</span> s][<span class="st">'error'</span>] <span class="cf">for</span> s <span class="kw">in</span> sectors]</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>bp2 <span class="op">=</span> ax2.boxplot(put_sector_data, labels<span class="op">=</span>sectors, patch_artist<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> patch, color <span class="kw">in</span> <span class="bu">zip</span>(bp2[<span class="st">'boxes'</span>], sector_colors):</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>    patch.set_facecolor(color)</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>    patch.set_alpha(<span class="fl">0.7</span>)</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>ax2.axhline(y<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>ax2.set_ylabel(<span class="st">'Pricing Error ($)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>ax2.set_title(<span class="st">'Put Options: Pricing Error by Sector'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-sector-analysis" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sector-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pde3_files/figure-html/fig-sector-analysis-output-1.png" width="1331" height="467" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sector-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Pricing Errors by Sector
</figcaption>
</figure>
</div>
</div>
</div>
<section id="interpretation-sector-analysis" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="interpretation-sector-analysis"><span class="header-section-number">4.5.1</span> Interpretation: Sector Analysis</h3>
<p>The box plots reveal sector-specific patterns in Black-Scholes pricing accuracy:</p>
<p><strong>Call Options (Left Panel):</strong></p>
<ol type="1">
<li><p><strong>Financial Sector (Blue):</strong> Median error near $5, relatively tight interquartile range, with some outliers above $50. The BS model consistently underprices financial call options.</p></li>
<li><p><strong>Healthcare Sector (Pink):</strong> Widest distribution with median around $5-10, but extreme outliers reaching $60+. High variability suggests sector-specific factors affect pricing.</p></li>
<li><p><strong>Technology Sector (Orange):</strong> Median close to zero with a tighter distribution than Healthcare. However, outliers exist on both sides, indicating occasional large deviations.</p></li>
</ol>
<p><strong>Put Options (Right Panel):</strong></p>
<ol type="1">
<li><p><strong>Financial Sector:</strong> Median around -$10, with errors ranging from -$60 to near zero. The BS model significantly overprices financial put options.</p></li>
<li><p><strong>Healthcare Sector:</strong> Similar pattern to Financial, with median around -$15 and wide variability.</p></li>
<li><p><strong>Technology Sector:</strong> <strong>Best performance</strong> with median near zero and the tightest distribution. This explains why AAPL (Technology) was the only stock where puts passed the t-test.</p></li>
</ol>
<p><strong>Sector Conclusions:</strong> - <strong>Technology stocks</strong> show the best alignment with Black-Scholes prices - <strong>Healthcare stocks</strong> show the highest variability and largest errors - <strong>Financial stocks</strong> show consistent bias (underpricing calls, overpricing puts)</p>
<hr>
</section>
</section>
<section id="market-vs-black-scholes-price-comparison" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="market-vs-black-scholes-price-comparison"><span class="header-section-number">4.6</span> Market vs Black-Scholes Price Comparison</h2>
<div id="cell-fig-market-vs-bs" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">6</span>))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Call options</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>ax1 <span class="op">=</span> axes[<span class="dv">0</span>]</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> sector, color <span class="kw">in</span> <span class="bu">zip</span>(sectors, sector_colors):</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> calls_with_sector[calls_with_sector[<span class="st">'sector'</span>] <span class="op">==</span> sector]</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    ax1.scatter(data[<span class="st">'bs_price'</span>], data[<span class="st">'market_price'</span>], alpha<span class="op">=</span><span class="fl">0.6</span>, </span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>                label<span class="op">=</span>sector, color<span class="op">=</span>color, s<span class="op">=</span><span class="dv">50</span>, edgecolor<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>max_val <span class="op">=</span> <span class="bu">max</span>(calls_results[<span class="st">'market_price'</span>].<span class="bu">max</span>(), calls_results[<span class="st">'bs_price'</span>].<span class="bu">max</span>())</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>ax1.plot([<span class="dv">0</span>, max_val], [<span class="dv">0</span>, max_val], <span class="st">'k--'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">'Perfect Fit'</span>)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>ax1.set_xlabel(<span class="st">'Black-Scholes Price ($)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">'Market Price ($)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>ax1.set_title(<span class="st">'Call Options: Market vs BS Price'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>ax1.legend()</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Put options</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>ax2 <span class="op">=</span> axes[<span class="dv">1</span>]</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> sector, color <span class="kw">in</span> <span class="bu">zip</span>(sectors, sector_colors):</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> puts_with_sector[puts_with_sector[<span class="st">'sector'</span>] <span class="op">==</span> sector]</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>    ax2.scatter(data[<span class="st">'bs_price'</span>], data[<span class="st">'market_price'</span>], alpha<span class="op">=</span><span class="fl">0.6</span>, </span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>                label<span class="op">=</span>sector, color<span class="op">=</span>color, s<span class="op">=</span><span class="dv">50</span>, edgecolor<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>max_val <span class="op">=</span> <span class="bu">max</span>(puts_results[<span class="st">'market_price'</span>].<span class="bu">max</span>(), puts_results[<span class="st">'bs_price'</span>].<span class="bu">max</span>())</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>ax2.plot([<span class="dv">0</span>, max_val], [<span class="dv">0</span>, max_val], <span class="st">'k--'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">'Perfect Fit'</span>)</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>ax2.set_xlabel(<span class="st">'Black-Scholes Price ($)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>ax2.set_ylabel(<span class="st">'Market Price ($)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>ax2.set_title(<span class="st">'Put Options: Market vs BS Price'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>ax2.legend()</span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-market-vs-bs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-market-vs-bs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pde3_files/figure-html/fig-market-vs-bs-output-1.png" width="1330" height="562" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-market-vs-bs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Market Price vs Black-Scholes Price Scatter Plot
</figcaption>
</figure>
</div>
</div>
</div>
<section id="interpretation-market-vs-bs-price-scatter" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1" class="anchored" data-anchor-id="interpretation-market-vs-bs-price-scatter"><span class="header-section-number">4.6.1</span> Interpretation: Market vs BS Price Scatter</h3>
<p>The scatter plots provide a visual assessment of how well Black-Scholes prices match market prices:</p>
<p><strong>Perfect Fit Line:</strong> The dashed diagonal line represents perfect agreement (Market Price = BS Price). Points above the line indicate BS underpricing; points below indicate BS overpricing.</p>
<p><strong>Call Options (Left Panel):</strong></p>
<ul>
<li>Most points lie <strong>above</strong> the perfect fit line</li>
<li>This confirms the BS model <strong>systematically underprices</strong> call options</li>
<li>Technology stocks (orange) cluster closest to the line at lower price levels</li>
<li>Healthcare and Financial stocks show larger deviations at higher prices</li>
<li>The underpricing becomes more pronounced for expensive options</li>
</ul>
<p><strong>Put Options (Right Panel):</strong></p>
<ul>
<li>Most points lie <strong>below</strong> the perfect fit line</li>
<li>This confirms the BS model <strong>systematically overprices</strong> put options</li>
<li>Technology stocks (orange) show the best fit, clustering around the line</li>
<li>Healthcare stocks (pink) show significant deviation below the line</li>
<li>The pattern suggests market participants pay less for puts than BS predicts</li>
</ul>
<p><strong>Key Insight:</strong> The systematic positioning of points relative to the perfect fit line indicates a <strong>consistent bias</strong> in the Black-Scholes model, not random error. This suggests market factors (like volatility skew or risk premiums) that the model doesn’t capture.</p>
<hr>
</section>
</section>
</section>
<section id="summary-and-conclusions" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Summary and Conclusions</h1>
<section id="summary-of-results" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="summary-of-results"><span class="header-section-number">5.1</span> Summary of Results</h2>
<div id="summary-table" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">80</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"SUMMARY OF PAIRED SAMPLE T-TEST RESULTS"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">80</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>summary_data <span class="op">=</span> []</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ticker <span class="kw">in</span> stock_info[<span class="st">'ticker'</span>]:</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    call_row <span class="op">=</span> calls_ttest[calls_ttest[<span class="st">'ticker'</span>] <span class="op">==</span> ticker].iloc[<span class="dv">0</span>]</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    put_row <span class="op">=</span> puts_ttest[puts_ttest[<span class="st">'ticker'</span>] <span class="op">==</span> ticker].iloc[<span class="dv">0</span>]</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    summary_data.append({</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Ticker'</span>: ticker,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Call p-value'</span>: call_row[<span class="st">'p_value'</span>],</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Call Sig?'</span>: call_row[<span class="st">'significant'</span>],</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Put p-value'</span>: put_row[<span class="st">'p_value'</span>],</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Put Sig?'</span>: put_row[<span class="st">'significant'</span>]</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>summary_df <span class="op">=</span> pd.DataFrame(summary_data)</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> summary_df.to_string(index<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>call_not_sig <span class="op">=</span> (calls_ttest[<span class="st">'significant'</span>] <span class="op">==</span> <span class="st">'No'</span>).<span class="bu">sum</span>()</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>put_not_sig <span class="op">=</span> (puts_ttest[<span class="st">'significant'</span>] <span class="op">==</span> <span class="st">'No'</span>).<span class="bu">sum</span>()</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">"</span> <span class="op">+</span> <span class="st">"="</span> <span class="op">*</span> <span class="dv">80</span>)</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"STATISTICAL SUMMARY"</span>)</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">80</span>)</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"""</span></span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a><span class="ss">CALL OPTIONS:</span></span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a><span class="ss">  • No significant difference: </span><span class="sc">{</span>call_not_sig<span class="sc">}</span><span class="ss"> out of </span><span class="sc">{</span><span class="bu">len</span>(calls_ttest)<span class="sc">}</span><span class="ss"> stocks (</span><span class="sc">{</span>call_not_sig<span class="op">/</span><span class="bu">len</span>(calls_ttest)<span class="op">*</span><span class="dv">100</span><span class="sc">:.0f}</span><span class="ss">%)</span></span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a><span class="ss">  • Significant difference: </span><span class="sc">{</span><span class="bu">len</span>(calls_ttest) <span class="op">-</span> call_not_sig<span class="sc">}</span><span class="ss"> out of </span><span class="sc">{</span><span class="bu">len</span>(calls_ttest)<span class="sc">}</span><span class="ss"> stocks (</span><span class="sc">{</span>(<span class="bu">len</span>(calls_ttest) <span class="op">-</span> call_not_sig)<span class="op">/</span><span class="bu">len</span>(calls_ttest)<span class="op">*</span><span class="dv">100</span><span class="sc">:.0f}</span><span class="ss">%)</span></span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a><span class="ss">PUT OPTIONS:</span></span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a><span class="ss">  • No significant difference: </span><span class="sc">{</span>put_not_sig<span class="sc">}</span><span class="ss"> out of </span><span class="sc">{</span><span class="bu">len</span>(puts_ttest)<span class="sc">}</span><span class="ss"> stocks (</span><span class="sc">{</span>put_not_sig<span class="op">/</span><span class="bu">len</span>(puts_ttest)<span class="op">*</span><span class="dv">100</span><span class="sc">:.0f}</span><span class="ss">%)</span></span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a><span class="ss">  • Significant difference: </span><span class="sc">{</span><span class="bu">len</span>(puts_ttest) <span class="op">-</span> put_not_sig<span class="sc">}</span><span class="ss"> out of </span><span class="sc">{</span><span class="bu">len</span>(puts_ttest)<span class="sc">}</span><span class="ss"> stocks (</span><span class="sc">{</span>(<span class="bu">len</span>(puts_ttest) <span class="op">-</span> put_not_sig)<span class="op">/</span><span class="bu">len</span>(puts_ttest)<span class="op">*</span><span class="dv">100</span><span class="sc">:.0f}</span><span class="ss">%)</span></span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a><span class="ss">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>================================================================================
SUMMARY OF PAIRED SAMPLE T-TEST RESULTS
================================================================================

Ticker  Call p-value Call Sig?  Put p-value Put Sig?
   BAC  1.817197e-03       Yes 9.236035e-06      Yes
   JPM  7.309289e-04       Yes 1.924905e-06      Yes
   WFC  9.353165e-04       Yes 2.046372e-07      Yes
   MRK  4.759804e-05       Yes 2.155100e-09      Yes
   PFE  1.660710e-02       Yes 1.286232e-11      Yes
   UNH  3.656221e-07       Yes 7.538276e-08      Yes
  AAPL  2.862982e-05       Yes 5.261225e-01       No
  MSFT  1.197965e-09       Yes 1.591778e-04      Yes
  NVDA  1.011702e-03       Yes 8.629607e-04      Yes

================================================================================
STATISTICAL SUMMARY
================================================================================

CALL OPTIONS:
  • No significant difference: 0 out of 9 stocks (0%)
  • Significant difference: 9 out of 9 stocks (100%)

PUT OPTIONS:
  • No significant difference: 1 out of 9 stocks (11%)
  • Significant difference: 8 out of 9 stocks (89%)
</code></pre>
</div>
</div>
</section>
<section id="conclusions" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="conclusions"><span class="header-section-number">5.2</span> Conclusions</h2>
<p>Based on the comprehensive empirical analysis using paired sample t-tests on nine stocks across three sectors (Financial, Healthcare, and Technology), this study reaches the following conclusions:</p>
<section id="primary-findings" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="primary-findings"><span class="header-section-number">5.2.1</span> Primary Findings</h3>
<ol type="1">
<li><p><strong>Call Options:</strong> The Black-Scholes model shows <strong>statistically significant pricing differences</strong> from market prices for <strong>all nine stocks</strong> (100%). The model consistently <strong>underprices</strong> call options, with mean errors ranging from $1.22 (NVDA) to $24.26 (UNH). Therefore, the Black-Scholes model <strong>cannot be reliably used</strong> to price call options in the current U.S. stock market.</p></li>
<li><p><strong>Put Options:</strong> The Black-Scholes model shows significant pricing differences for <strong>eight out of nine stocks</strong> (89%). Only <strong>AAPL</strong> (p = 0.5261) showed no significant difference. The model consistently <strong>overprices</strong> put options, with mean errors ranging from -$0.34 (AAPL) to -$28.81 (UNH). Therefore, the Black-Scholes model is <strong>not suitable</strong> for pricing put options, except potentially for certain Technology stocks like AAPL.</p></li>
<li><p><strong>Sector Differences:</strong></p>
<ul>
<li><strong>Technology sector</strong> shows the best alignment with Black-Scholes prices, with smaller and more consistent errors</li>
<li><strong>Healthcare sector</strong> shows the largest errors and highest variability</li>
<li><strong>Financial sector</strong> shows moderate errors with consistent bias patterns</li>
</ul></li>
</ol>
</section>
<section id="comparison-with-prior-research" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="comparison-with-prior-research"><span class="header-section-number">5.2.2</span> Comparison with Prior Research</h3>
<p>Our findings <strong>contrast</strong> with Salami (2024), who found that the Black-Scholes model works better for call options (7 out of 9 stocks) than put options (4 out of 9 stocks). Our analysis shows:</p>
<ul>
<li><strong>Calls</strong>: 0 out of 9 stocks show no significant difference (vs.&nbsp;7/9 in Salami 2024)</li>
<li><strong>Puts</strong>: 1 out of 9 stocks show no significant difference (vs.&nbsp;4/9 in Salami 2024)</li>
</ul>
<p>This discrepancy may be attributed to:</p>
<ol type="1">
<li><strong>Different market conditions</strong>: Our study uses current market data, while Salami (2024) used data from May-June 2022</li>
<li><strong>Market volatility regime</strong>: Current market conditions may feature different volatility dynamics</li>
<li><strong>Economic factors</strong>: Interest rate environment, inflation expectations, and market sentiment have changed significantly</li>
</ol>
</section>
<section id="possible-reasons-for-model-mispricing" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="possible-reasons-for-model-mispricing"><span class="header-section-number">5.2.3</span> Possible Reasons for Model Mispricing</h3>
<p>The systematic mispricing observed can be attributed to violations of Black-Scholes assumptions:</p>
<ol type="1">
<li><strong>Volatility is not constant</strong>: The volatility smile/skew observed in options markets contradicts the constant volatility assumption</li>
<li><strong>Returns are not normally distributed</strong>: Real market returns exhibit fat tails and negative skewness</li>
<li><strong>Markets are not frictionless</strong>: Transaction costs, bid-ask spreads, and liquidity constraints affect prices</li>
<li><strong>Interest rates are dynamic</strong>: The assumption of constant risk-free rates is violated in current market conditions</li>
<li><strong>Early exercise premium</strong>: American-style options may have early exercise value not captured by the European-style BS model</li>
</ol>
<hr>
</section>
</section>
</section>
<section id="future-work" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Future Work</h1>
<p>Based on the findings and limitations of this study, several directions for future research are recommended:</p>
<section id="alternative-pricing-models" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="alternative-pricing-models"><span class="header-section-number">6.1</span> 1. Alternative Pricing Models</h2>
<ul>
<li><strong>Heston Stochastic Volatility Model</strong>: Incorporate stochastic volatility to address the volatility smile</li>
<li><strong>SABR Model</strong>: Consider the SABR (Stochastic Alpha, Beta, Rho) model for interest rate derivatives</li>
<li><strong>Jump-Diffusion Models</strong>: Implement Merton’s jump-diffusion model to capture sudden price movements</li>
<li><strong>Local Volatility Models</strong>: Use Dupire’s local volatility framework</li>
</ul>
</section>
<section id="extended-empirical-analysis" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="extended-empirical-analysis"><span class="header-section-number">6.2</span> 2. Extended Empirical Analysis</h2>
<ul>
<li><strong>Longer Time Period</strong>: Conduct analysis over multiple years to assess model performance across different market cycles</li>
<li><strong>More Stocks</strong>: Expand the sample to include mid-cap and small-cap stocks</li>
<li><strong>Different Markets</strong>: Compare results across international markets (European, Asian exchanges)</li>
<li><strong>Different Asset Classes</strong>: Test the model on index options, ETF options, and commodity options</li>
</ul>
</section>
<section id="machine-learning-approaches" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="machine-learning-approaches"><span class="header-section-number">6.3</span> 3. Machine Learning Approaches</h2>
<ul>
<li><strong>Neural Network Pricing</strong>: Develop deep learning models for option pricing</li>
<li><strong>Ensemble Methods</strong>: Combine multiple models to improve pricing accuracy</li>
<li><strong>Feature Engineering</strong>: Incorporate additional market factors (sentiment, order flow, macroeconomic indicators)</li>
</ul>
</section>
<section id="market-condition-analysis" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="market-condition-analysis"><span class="header-section-number">6.4</span> 4. Market Condition Analysis</h2>
<ul>
<li><strong>Crisis Periods</strong>: Study model performance during market stress (COVID-19, 2008 financial crisis)</li>
<li><strong>Volatility Regimes</strong>: Analyze pricing accuracy in high vs.&nbsp;low volatility environments</li>
<li><strong>Interest Rate Environments</strong>: Compare results across different monetary policy regimes</li>
</ul>
</section>
<section id="practical-applications" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="practical-applications"><span class="header-section-number">6.5</span> 5. Practical Applications</h2>
<ul>
<li><strong>Trading Strategy Development</strong>: Develop strategies that exploit systematic mispricing</li>
<li><strong>Risk Management</strong>: Quantify the impact of model error on hedging effectiveness</li>
<li><strong>Model Calibration</strong>: Develop improved calibration techniques for practical use</li>
</ul>
<hr>
</section>
</section>
<section id="references" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> References</h1>
<ol type="1">
<li><p>Black, F., &amp; Scholes, M. (1973). The pricing of options and corporate liabilities. <em>Journal of Political Economy</em>, 81(3), 637-654.</p></li>
<li><p>Merton, R. C. (1973). Theory of rational option pricing. <em>Bell Journal of Economics and Management Science</em>, 4(1), 141-183.</p></li>
<li><p>Corrado, C. J., &amp; Miller, T. W. (1996). A note on a simple, accurate formula to compute implied standard deviations. <em>Journal of Banking &amp; Finance</em>, 20(3), 595-603.</p></li>
<li><p>Salami, M. F. (2024). Empirical examination of the Black–Scholes model: evidence from the United States stock market. <em>Frontiers in Applied Mathematics and Statistics</em>, 10, 1216386.</p></li>
<li><p>Ghasemi, A., &amp; Zahediasl, S. (2012). Normality tests for statistical analysis: a guide for non-statisticians. <em>International Journal of Endocrinology and Metabolism</em>, 10(2), 486-489.</p></li>
<li><p>Hull, J. C. (2018). <em>Options, Futures, and Other Derivatives</em> (10th ed.). Pearson Education.</p></li>
<li><p>Heston, S. L. (1993). A closed-form solution for options with stochastic volatility with applications to bond and currency options. <em>The Review of Financial Studies</em>, 6(2), 327-343.</p></li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>